# Generated by Django 5.0.6 on 2024-05-23 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book',
        ),
    ]
