# Generated by Django 5.0.6 on 2024-05-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('book_author', models.CharField(max_length=30)),
                ('book_category', models.CharField(max_length=20)),
                ('book_img', models.ImageField(upload_to='book_photos')),
            ],
        ),
    ]
