# Generated by Django 5.0.6 on 2024-05-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_descrption',
            field=models.CharField(default='book is good', max_length=200),
        ),
    ]
