# Generated by Django 5.0.6 on 2024-05-24 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_book_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='borrowed',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.book')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
            bases=('books.book', models.Model),
        ),
    ]
