# Generated by Django 5.0.6 on 2024-05-24 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_borrowed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='borrowed',
        ),
    ]
