# Generated by Django 5.0.6 on 2024-05-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='pressed_on',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=6)),
                ('title', models.CharField(max_length=30)),
                ('book_author', models.CharField(max_length=30)),
                ('book_category', models.CharField(max_length=20)),
                ('book_img', models.ImageField(upload_to='book_photos')),
                ('book_descrption', models.CharField(default='book is good', max_length=200)),
                ('is_borrowed', models.BooleanField(default=False)),
            ],
        ),
    ]
