# Generated by Django 5.0.6 on 2024-06-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_pressed_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pressed_on',
        ),
    ]
